openapi: 3.0.1
info:
  title: Escala API - Crescer e aprender
  description: |-
    Escala API é uma API desenvolvida para facilitar o cadastro e o controle de escalas de voluntários do projeto social Crescer e Aprender. Esse projeto tem como missão oferecer aulas gratuitas de Informática, Matemática e Língua Portuguesa para crianças em situação de vulnerabilidade social.

    Links úteis:
    - [Repositório no GitHub](https://github.com/luizhenrique3651/escala-crescer-aprender-api)
    - [Instagram do projeto Crescer e Aprender](https://www.instagram.com/proj_crescereaprender/)
  contact:
    email: uizhenrique@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.12


servers:
  - url: http://localhost:8080/

paths:
  /crescer-aprender/escala:
    get:
      summary: Lista todas as escalas
      tags: [Escalas]
      responses:
        '200':
          description: Lista de escalas encontrada
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Escala'
        '204':
          description: Nenhuma escala encontrada
    post:
      summary: Cria uma nova escala
      tags: [Escalas]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Escala'
      responses:
        '200':
          description: Escala criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Escala'
        '400':
          description: Escala já existe para o mês/ano informado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Escala'

  /crescer-aprender/escala/{id}:
    get:
      summary: Busca uma escala por ID
      tags: [Escalas]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Escala encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Escala'
        '404':
          description: Escala não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Escala'
    put:
      summary: Atualiza uma escala existente
      tags: [Escalas]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Escala'
      responses:
        '200':
          description: Escala atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Escala'
        '404':
          description: Escala não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Escala'
    delete:
      summary: Remove uma escala
      tags: [Escalas]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Escala removida com sucesso
        '404':
          description: Escala não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Escala'

  /crescer-aprender/escala/buscar-por-mes-ano-voluntario:
    post:
      summary: Busca uma escala por mês, ano e voluntário
      tags: [Escalas]
      parameters:
        - name: mes
          in: query
          required: true
          schema:
            type: integer
        - name: ano
          in: query
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Voluntario'
      responses:
        '200':
          description: Escala encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Escala'
        '404':
          description: Escala não encontrada

components:
  schemas:
    Escala:
      type: object
      properties:
        id:
          type: integer
          example: 1
        mes:
          type: integer
          example: 6
        ano:
          type: integer
          example: 2025
        datas:
          type: array
          items:
            type: string
            format: date
          example: ["2025-06-01", "2025-06-08"]
        voluntarios:
          type: array
          items:
            $ref: '#/components/schemas/Voluntario'
        errorMessage:
          type: string
          example: Escala já existe para o mês 6 e ano 2025

    Voluntario:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: João da Silva
        email:
          type: string
          example: joao@email.com
        senha:
          type: string
          example: "123456"
        datasDisponiveis:
          type: array
          items:
            type: string
            format: date
          example: ["2025-06-01", "2025-06-15"]
